"""Camada de abstração e transporte de modelos LLM."""

from .provider import (
    BaseLLMProvider,
    CancellationToken,
    LLMResponse,
    ModelToolConversation,
    ModelToolConversationTurn,
    ModelToolResult,
    OpenAICompatibleHTTPProvider,
    ProviderAuthError,
    ProviderCancelledError,
    ProviderContinuationState,
    ProviderError,
    ProviderInvalidRequestError,
    ProviderNotImplementedError,
    ProviderRateLimitError,
    ProviderResponseError,
    ProviderTimeoutError,
    ProviderUnavailableError,
    ToolCall,
)
from .registry import ProviderConfiguration, ProviderRegistry
from .router import (
    ModelEgressDeniedError,
    ModelResponseBudgetExceededError,
    ModelResponseCancelledError,
    ModelRouteConfiguration,
    ModelRouter,
    ModelRoutingConfigurationError,
    ModelRoutingIntegrityError,
    ModelsConfiguration,
)

__all__ = [
    "BaseLLMProvider",
    "CancellationToken",
    "LLMResponse",
    "ModelEgressDeniedError",
    "ModelResponseBudgetExceededError",
    "ModelResponseCancelledError",
    "ModelRouteConfiguration",
    "ModelRouter",
    "ModelRoutingConfigurationError",
    "ModelRoutingIntegrityError",
    "ModelToolConversation",
    "ModelToolConversationTurn",
    "ModelToolResult",
    "ModelsConfiguration",
    "OpenAICompatibleHTTPProvider",
    "ProviderAuthError",
    "ProviderCancelledError",
    "ProviderConfiguration",
    "ProviderContinuationState",
    "ProviderError",
    "ProviderInvalidRequestError",
    "ProviderNotImplementedError",
    "ProviderRateLimitError",
    "ProviderRegistry",
    "ProviderResponseError",
    "ProviderTimeoutError",
    "ProviderUnavailableError",
    "ToolCall",
]
